### ISSUE TITLE
[FEAT] 초기 진입 화면 (차로 들어가기)

### ISSUE THREAD

**Issue by ChaeDoll** [ChaeDoll/90DegreesCelsius#1]
### Description
- 처음 유저가 기기를 착용했을 때, MR 환경에서 유저가 경험할 차의 이름을 나타내준다. 
- 티 카드를 유저에게 가까이 하면 트리거로서 경험이 시작됨.

### To-Do List
- [ ] MR 환경에서 티 카드와 함께 시작하기
- [ ] Grabbable한 티 카드(임시) 만들기
- [ ] 티 카드를 가까이 하면 VR 경험으로 전환
